# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-19 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtname', models.CharField(max_length=30)),
                ('mtteam', models.CharField(blank=True, max_length=30, null=True)),
                ('mtdate', models.DateTimeField()),
                ('mtloca', models.CharField(blank=True, max_length=30, null=True)),
                ('mthost', models.CharField(blank=True, max_length=20, null=True)),
                ('mtmemo', models.CharField(blank=True, max_length=100, null=True)),
                ('crdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('crdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('crdate', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='snctrd.Meetings')),
                ('menu', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='snctrd.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('crdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamcode', models.CharField(max_length=10)),
                ('teamname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snctrd.Shop'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='snctrd.Team'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='shop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='snctrd.Shop'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='snctrd.Team'),
        ),
    ]
